ALTER TABLE categories
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;

ALTER TABLE green_certificates
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;

ALTER TABLE products
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;

ALTER TABLE materials
ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;
